{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/csmith/dotege"
    "Tag" (github_tag "csmith/dotege")
    "Package" "./cmd/dotege"
    "LinkerFlags" "-X main.GitSHA=$(git rev-parse --short HEAD)"
    "BuildFlags" "-tags lego_httpreq"
    "BinaryName" "dotege"
    "ExtraDirs" (arr "config" "certs" "output")
)}}

COPY --from=build /data /
COPY --from=build /work/templates /templates

VOLUME /data/config
VOLUME /data/certs
VOLUME /data/output
