resources:
  - name: daily
    type: time
    icon: clock-outline

  - name: git
    type: git
    icon: github
    check_every: never
    webhook_token: ((webhook.token))
    source:
      uri: https://github.com/csmith/dockerfiles
      branch: master
      username: ((github.user))
      password: ((github.token))

  - name: golang-image
    type: docker-image
    source:
      repository: reg.c5h.io/golang
      username: ((registry.user))
      password: ((registry.password))

jobs:
  - name: update
    plan:
      - get: git
      - get: golang-image
      - get: daily
        trigger: true
      - task: check
        image: golang-image
        config:
          platform: linux
          inputs:
            - name: git
              path: src
          run:
            path: /bin/sh
            args:
              - -c
              - |
                cd src
                apk add --no-progress --no-cache buildah
                git config user.email concourse@chameth.com
                git config user.name "Concourse CI"
                go run ./cmd -registry-user "((registry.user))" -registry-pass "((registry.password))"
      - put: git
        params:
          repository: git
