{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/greboid/irc-bot"
    "Tag" (github_tag "greboid/irc-bot")
    "Package" "./cmd/bot"
    "BinaryName" "irc-bot"
)}}

EXPOSE 8080
