{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/csmith/irc-distribution"
    "Tag" (github_tag "csmith/irc-distribution")
    "Package" "./cmd/distribution"
    "BinaryName" "irc-distribution"
)}}