{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/greboid/httpredirect"
    "Tag" (github_tag "greboid/httpredirect")
    "Package" "."
    "BinaryName" "httpredirect"
)}}

EXPOSE 8080
