{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/cutlerydrawer/linx-server"
    "Tag" (github_tag "cutlerydrawer/linx-server")
    "Package" "."
    "BinaryName" "linx-server"
    "ExtraDirs" (arr "files" "meta")
)}}

COPY --from=build /data /data

VOLUME ["/data/files", "/data/meta"]
EXPOSE 8080
ENTRYPOINT ["/linx-server", "-bind=0.0.0.0:8080", "-filespath=/data/files/", "-metapath=/data/meta/"]
CMD ["-sitename=linx", "-allowhotlink"]
