FROM reg.c5h.io/arch AS build

RUN set -eux; \
    # Install packages we need to bootstrap an image
    pacman --noconfirm --needed -Syu extra/devtools extra/fakechroot core/fakeroot; \
    # Bodge the hooks (?)
    mkdir -vp /build/alpm-hooks/usr/share/libalpm/hooks; \
	find /usr/share/libalpm/hooks -exec ln -sf /dev/null /build/alpm-hooks{} \;; \
	# Create skeleton for pacman
    mkdir -vp /build/var/lib/pacman /build/etc/pacman.d; \
	install -Dm644 /usr/share/devtools/pacman-extra.conf /build/etc/pacman.conf; \
	# Configure pacman to avoid extracting stuff we don't care about
	echo -e '[options]\nNoExtract = \
	    usr/lib/systemd/** \
	    usr/share/audit/sample-rules/** \
	    usr/share/bash-completion/** \
	    usr/share/fish/vendor_completions.d/** \
	    usr/share/gnupg/help*.txt \
	    usr/share/pixmaps/** \
	    usr/share/terminfo/** \
	    usr/share/help/* \
        usr/share/iana-etc/* \
	    usr/share/gtk-doc/html/* \
	    usr/share/doc/* \
	    usr/share/locale/* \
	    !usr/share/locale/locale.alias \
	    usr/share/X11/locale/* \
	    usr/share/i18n/* \
	    !*locale*/en_US/* \
	    !usr/share/i18n/charmaps/UTF-8.gz \
	    !usr/share/*locales/en_GB \
	    !usr/share/*locales/en_US \
	    !usr/share/*locales/i18n \
	    !usr/share/*locales/i18n_ctype \
	    !usr/share/*locales/iso14651_* \
	    !usr/share/*locales/locale.alias \
	    !usr/share/*locales/translit_* \
	    usr/share/man/* \
	    usr/share/info/* \
	    usr/share/vim/vim*/lang/*' >> /build/etc/pacman.conf; \
    # Sync packages
    fakechroot -- fakeroot -- pacman -Sy -r /build \
        --noconfirm --dbpath /build/var/lib/pacman \
        --config /build/etc/pacman.conf \
        --noscriptlet \
        --hookdir /build/alpm-hooks/usr/share/libalpm/hooks/ \
        {{range $key, $value := .Packages -}}
        {{ $key }}={{ $value }} \
        {{end}}; \
    # Drop in some config files
    echo 'en_US.UTF-8 UTF-8' > /build/etc/locale.gen; \
    echo 'LANG=en_US.UTF-8' > /build/etc/locale.conf; \
    echo 'Server = https://mirrors.melbourne.co.uk/archlinux/$repo/os/$arch' > /build/etc/pacman.d/mirrorlist; \
    # Update certificates, locales, etc
    fakechroot -- fakeroot -- chroot /build update-ca-trust; \
	fakechroot -- fakeroot -- chroot /build locale-gen; \
	fakechroot -- fakeroot -- chroot /build pacman-key --init; \
	fakechroot -- fakeroot -- chroot /build pacman-key --populate; \
	# Remove passwordless login for root (see CVE-2019-5021 for reference)
	sed -i -e 's/^root::/root:!:/' /build/etc/shadow; \
	# Remove a bunch of things we don't want to keep in the image
	rm -rf \
	    /build/alpm-hooks \
	    /build/dev \
	    /build/etc/pacman.d/gnupg/openpgp-revocs.d/* \
	    /build/etc/pacman.d/gnupg/private-keys-v1.d/* \
	    /build/etc/pacman.d/gnupg/pubring.gpg~ \
	    /build/etc/pacman.d/gnupg/S.* \
	    /build/etc/resolv.conf \
	    /build/proc \
	    /build/sys \
	    /build/var/lib/pacman/sync\
	    /build/var/log/*; \
	# Clobber all the timestamps to make the build more reproducible
    find /build -exec touch --date=@0 {} \;;

FROM scratch
COPY --from=build /build/ /
CMD ["/bin/bash"]
