{{template "complete-go-image.gotpl" (map
    "Repo" "https://github.com/greboid/irc-notifier"
    "Tag" (github_tag "greboid/irc-notifier")
    "Package" "./cmd/notifier"
    "BinaryName" "irc-notifier"
)}}